### ISSUE TITLE
big5 encoding currently fails tests in some cirumstances

### ISSUE THREAD

**Issue by ilyvion** [alexschrod/encoding-next#1]
The `codec::tradchinese::bigfive2003_tests::test_encoder_valid` and `big5::tests::test_correct_table` tests fail when the `no-optimized-legacy-encoding` feature is enabled, which suggests that there's something wrong with the big5 encoding (or tests) when using the legacy encoding.
```
features: [no-optimized-legacy-encoding]

cause:
thread 'codec::tradchinese::bigfive2003_tests::test_encoder_valid' panicked at 'raw_feed should push [249, 249], but instead pushed [162, 164]'

stack backtrace:
   0: rust_begin_unwind
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/panicking.rs:142:14
   2: encoding::codec::tradchinese::bigfive2003_tests::test_encoder_valid
             at ./src/codec/tradchinese.rs:204:9
   3: encoding::codec::tradchinese::bigfive2003_tests::test_encoder_valid::{{closure}}
             at ./src/codec/tradchinese.rs:191:5
   4: core::ops::function::FnOnce::call_once
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/ops/function.rs:248:5
   5: core::ops::function::FnOnce::call_once
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
```
features: [no-optimized-legacy-encoding]

cause:
thread 'big5::tests::test_correct_table' panicked at 'assertion failed: `(left == right)`
  left: `5248`,
 right: `18975`'

stack backtrace:
   0: rust_begin_unwind
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/panicking.rs:181:5
   4: encoding_index_tradchinese::big5::tests::test_correct_table
             at /home/runner/work/encoding-next/encoding-next/encoding_index_tests/index_tests.rs:83:34
   5: encoding_index_tradchinese::big5::tests::test_correct_table::{{closure}}
             at /home/runner/work/encoding-next/encoding-next/encoding_index_tests/index_tests.rs:78:9
   6: core::ops::function::FnOnce::call_once
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/ops/function.rs:248:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/f2d93935ffba3ab9d7ccb5300771a2d29b4c8bf3/library/core/src/ops/function.rs:248:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by ilyvion** [comment]
The `codec::tradchinese::bigfive2003_tests::test_encoder_valid` error shows up since 496823171f15d9b9446b2ec3fb7765f22346256b and the `big5::tests::test_correct_table` one shows up since 24c62c4040cb55f813e519e72535ad9c0a181466, which is a merge of 2591e2a1d0d8bcafcc468331420ced28eb00e493.

**Comment by ilyvion** [comment]
For the time being, I have just hardcoded the specific code points that were failing;
https://github.com/alexschrod/encoding-next/blob/40ed60a8d4611a94833cee56c1227ba222c336b5/encoding-index-tradchinese/big5.rs#L3444-L3456
which means that the encoding now passes its tests. While not a satisfying solution, I have published it as a patch to the original publishing of the crate, which at least means that users shouldn't be getting incorrect encoding if they use the crate.

I'll be leaving the issue open until a proper fix is in place.
